TRT-Conseil/src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JobRepository::class)
 */
class Job
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_contrat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $time;

    /**
     * @ORM\Column(type="integer")
     */
    private $salary;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $to_apply;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_accepted;


    /**
     * @ORM\ManyToOne(targetEntity=Recruiter::class, inversedBy="jobs")
     * @ORM\JoinColumn(nullable=false , onDelete="CASCADE" , unique=false)
     */
    private  $recruiter;

    // , orphanRemoval=true
    /**
     * @ORM\ManyToMany(targetEntity=Candidate::class, mappedBy="apply_job" )
     */
    private $candidates;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $place;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function __construct()
    {
        $this->candidates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTypeContrat(): ?string
    {
        return $this->type_contrat;
    }

    public function setTypeContrat(string $type_contrat): self
    {
        $this->type_contrat = $type_contrat;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }


    public function setTime(int $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(int $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getToApply(): ?bool
    {
        return $this->to_apply;
    }

    public function setToApply(?bool $to_apply): self
    {
        $this->to_apply = $to_apply;

        return $this;
    }

    public function getIsAccepted(): ?bool
    {
        return $this->is_accepted;
    }

    public function setIsAccepted(?bool $is_accepted): self
    {
        $this->is_accepted = $is_accepted;

        return $this;
    }


    /**
     * @return Collection|Candidate[]
     */
    public function getCandidates(): Collection
    {
        return $this->candidates;
    }

    public function addCandidate(Candidate $candidate): self
    {
        if (!$this->candidates->contains($candidate)) {
            $this->candidates[] = $candidate;
            $candidate->addApplyJob($this);
        }

        return $this;
    }

    public function removeCandidate(Candidate $candidate): self
    {
        if ($this->candidates->removeElement($candidate)) {
            $candidate->removeApplyJob($this);
        }

        return $this;
    }

    public function __toString()
    {
        // to show the name of the Category in the select
        return (string) $this->title;
        // to show the id of the Category in the select
        // return $this->id;
    }


//: ?Recruiter
        public function getRecruiter()
    {
      return $this->recruiter;
    }

    // ?Recruiter
    public function setRecruiter( $recruiter): self
    {
      $this->recruiter = $recruiter;

      return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }



}

TRT-Conseil/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_accepted;

    /**
     * @ORM\OneToMany(targetEntity=Admin::class, mappedBy="user")
     */
    private $admins;

    /**
     * @ORM\OneToMany(targetEntity=Recruiter::class, mappedBy="user")
     */
    private $recruiters;

    /**
     * @ORM\OneToMany(targetEntity=Candidate::class, mappedBy="user")
     */
    private $candidates;

    /**
     * @ORM\OneToMany(targetEntity=Consultant::class, mappedBy="user")
     */
    private $consultants;

    public function __construct()
    {
        $this->admins = new ArrayCollection();
        $this->recruiters = new ArrayCollection();
        $this->candidates = new ArrayCollection();
        $this->consultants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
     /*   if ($this->email === 'chaminadepierre.24@gmail.com') {
            $roles = $this->roles;
            $roles[] = 'ROLE_ADMIN';
            return array_unique($roles);
        }
*/
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
    #    $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }


    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getIsAccepted(): ?bool
    {
        return $this->is_accepted;
    }

    public function setIsAccepted(bool $is_accepted): self
    {
        $this->is_accepted = $is_accepted;

        return $this;
    }

    /**
     * @return Collection|Admin[]
     */
    public function getAdmins(): Collection
    {
        return $this->admins;
    }

    public function addAdmin(Admin $admin): self
    {
        if (!$this->admins->contains($admin)) {
            $this->admins[] = $admin;
            $admin->setUser($this);
        }

        return $this;
    }

    public function removeAdmin(Admin $admin): self
    {
        if ($this->admins->removeElement($admin)) {
            // set the owning side to null (unless already changed)
            if ($admin->getUser() === $this) {
                $admin->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Recruiter[]
     */
    public function getRecruiters(): Collection
    {
        return $this->recruiters;
    }

    public function addRecruiter(Recruiter $recruiter): self
    {
        if (!$this->recruiters->contains($recruiter)) {
            $this->recruiters[] = $recruiter;
            $recruiter->setUser($this);
        }

        return $this;
    }

    public function removeRecruiter(Recruiter $recruiter): self
    {
        if ($this->recruiters->removeElement($recruiter)) {
            // set the owning side to null (unless already changed)
            if ($recruiter->getUser() === $this) {
                $recruiter->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Candidate[]
     */
    public function getCandidates(): Collection
    {
        return $this->candidates;
    }

    public function addCandidate(Candidate $candidate): self
    {
        if (!$this->candidates->contains($candidate)) {
            $this->candidates[] = $candidate;
            $candidate->setUser($this);
        }

        return $this;
    }

    public function removeCandidate(Candidate $candidate): self
    {
        if ($this->candidates->removeElement($candidate)) {
            // set the owning side to null (unless already changed)
            if ($candidate->getUser() === $this) {
                $candidate->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Consultant[]
     */
    public function getConsultants(): Collection
    {
        return $this->consultants;
    }

    public function addConsultant(Consultant $consultant): self
    {
        if (!$this->consultants->contains($consultant)) {
            $this->consultants[] = $consultant;
            $consultant->setUser($this);
        }

        return $this;
    }

    public function removeConsultant(Consultant $consultant): self
    {
        if ($this->consultants->removeElement($consultant)) {
            // set the owning side to null (unless already changed)
            if ($consultant->getUser() === $this) {
                $consultant->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        // to show the name of the Category in the select
        return (string) $this->email;
        // to show the id of the Category in the select
        // return $this->id;
    }
}

TRT-Conseil/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
           # ->add('email')
          #  ->add('roles')
          #  ->add('password')
            ->add('is_accepted' , null, [
                'label'=>'Cocher la case pour accepter l\'utilisateur'
           ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

TRT-Conseil/src/Controller/CONSULTANT/UserController.php
<?php

namespace App\Controller\CONSULTANT;

use App\Entity\Job;
use App\Entity\User;
use App\Form\JobConsultantType;
use App\Form\JobType;
use App\Form\UserType;
use App\Repository\JobRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/consultant")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository , JobRepository $jobRepository): Response
    {


        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
            'jobs' => $jobRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }


    /**
     * @Route("jobs/{id}/edit", name="job_edit_consultant", methods={"GET", "POST"})
     */
    public function editJobs(Request $request, Job $job, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(JobConsultantType::class, $job);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/editJobs.html.twig', [
            'job' => $job,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }




}

TRT-Conseil/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Supprimer</button>
</form>

TRT-Conseil/templates/user/_form.html.twig
{{ form_start(form) }}
   {# {{ form_widget(form) }} #}
<div>
    <p><strong>Email</strong> : {{ user.email }} <br></p>
    <p><strong>Accepter l'utilisateur</strong> : {{ form_widget(form.is_accepted) }} </p>
</div>
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

TRT-Conseil/templates/user/approvingToApply.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jobs/candidats{% endblock %}

{% block body %}
    {{ form_start(form) }}
   <div>
       <p>Approuvez la demande de candidature : {{ form_widget(form.toApply) }} <strong>Attention</strong>, si vous n'approuvez pas la candidature, le recruteur ne recevra pas de mail avec les informations du candidat.</p>
       <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
   </div>
    {{ form_end(form) }}
    <p><a href="{{ path('to_apply_job') }}" class="float-end">Retour à la liste</a></p>


{% endblock %}

TRT-Conseil/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'utilisateur{% endblock %}

{% block body %}
    <h1>Accepter ou non l'utilisateur</h1>
{#
  {{ include('user/_form.html.twig', {'button_label': 'Mettre à jour'}) }} #}
    {{ form_start(form) }}
    {# {{ form_widget(form) }} #}
    <div>
        <p><strong>Email</strong> : {{ user.email }} <br></p>
        <p><strong>Accepter l'utilisateur</strong> : {{ form_widget(form.is_accepted) }} </p>
    </div>
    <button class="btn btn-primary">{{ button_label|default('Mettre à jour') }}</button>
    {{ form_end(form) }}
    <a class=" float-end" href="{{ path('user_index') }}">Retour à la liste</a>

    {#  Je ne souhaite pas que le consultant puisse supprimer des utilisateur
    {{ include('user/_delete_form.html.twig') }}
    #}
{% endblock %}

TRT-Conseil/templates/user/editJobs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Accepter ou refuser le job </h1>
        <p><strong>Nom du job : </strong>{{ job.title }}</p>
    {{ form_start(form) }}
    <p>{{ form_widget(form.is_accepted) }} (Cocher la case pour accepter l'utilisateur)</p>

    <button class="btn btn-primary">{{ button_label|default('Mettre a jour') }}</button>
    <a class=" float-end" href="{{ path('user_index') }}">Retour à la liste</a>


    {{ form_end(form) }}
{% endblock %}

TRT-Conseil/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}

    <div>
        <p>Afin de faciliter vos recherches, vous pouvez vous rendre directement vers les <a href="#job-non-accepte">Jobs
                non acceptés</a> ou vers les <a href="#Utilisateurs-non-acceptés">Utilisateurs non acceptés</a> <a
                    href="{{ path('app') }}" class=" float-end">Retour à la page d'accueil</a></p>
    </div>

    <h1 id="Utilisateurs-non-acceptés">Utilisateurs non acceptés </h1>

    <table class="table">
        <thead>
        <tr>
            <th>Email</th>
            <th>Roles</th>
            <th>Utilisateur accepté</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            {% if user.roles != ["ROLE_ADMIN"] and user.roles != ["ROLE_CONSULTANT"] %}
                {% if user.isAccepted == false %}
                    <tr>
                        <td>{{ user.email }}</td>
                        <td>
                            {% if user.roles == ["ROLE_ADMIN"] %}
                            Administrateur
                            {% elseif user.roles == ["ROLE_CONSULTANT"] %}
                            Consultant
                            {% elseif user.roles == ["ROLE_RECRUITEUR"] %}
                            Recruteur
                            {% elseif user.roles == ["ROLE_CANDIDAT"] %}
                            Candidat
                            {% else %}
                            {{ user.roles ? user.roles|json_encode : '' }}</td>
                        {% endif %}

                        <td>{{ user.isAccepted ? 'Oui ✅' : 'Non ❌' }}</td>
                        <td>
                            <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-success">Modifier</a>
                        </td>
                    </tr>
                {% endif %}
            {% endif %}
        {% endfor %}
        </tbody>
    </table>



    <h1>Utilisateurs acceptés</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Email</th>
            <th>Roles</th>
            <th>Utilisateur accepté</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            {% if user.roles != ["ROLE_ADMIN"] and user.roles != ["ROLE_CONSULTANT"] %}
                {% if user.isAccepted == true %}
                    <tr>
                        <td>{{ user.email }}</td>
                        <td> {% if user.roles == ["ROLE_ADMIN"] %}
                                Administrateur
                            {% elseif user.roles == ["ROLE_CONSULTANT"] %}
                                Consultant
                            {% elseif user.roles == ["ROLE_RECRUITEUR"] %}
                                Recruteur
                            {% elseif user.roles == ["ROLE_CANDIDAT"] %}
                                Candidat
                            {% else %}
                                {{ user.roles ? user.roles|json_encode : '' }}
                            {% endif %}</td>
                        <td>{{ user.isAccepted ? 'Oui ✅' : 'Non ❌' }}</td>
                        <td>
                            <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-success">Modifier</a>
                        </td>
                    </tr
                {% endif %}
            {% endif %}
        {% endfor %}
        </tbody>
    </table>


    <h1 class="mt-5" id="job-non-accepte">Liste des annonces qui ont été acceptées par nos équipes :</h1>


    <table class="table">
        <thead>
        <tr>
            <th>Titre de l'annonce</th>
            <th>Description du Poste</th>
            <th>Lieu</th>
            <th>Type de contrat</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Nombre d'heures semaine</th>
            <th>Salaires mensuel</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for job in jobs %}
            {% if job.isAccepted == true %}
                <tr>
                    <td>{{ job.title }}</td>
                    <td>{{ job.description }}</td>
                    <td>{{ job.place }}</td>
                    <td>{{ job.typeContrat }}</td>
                    <td>{{ job.startDate ? job.startDate|date('d-m-Y') : '' }}</td>
                    <td>{{ job.endDate ? job.endDate|date('d-m-Y') : 'Pas de date de fin de contrat' }}</td>
                    <td>{{ job.time }}</td>
                    <td>{{ job.salary }}€</td>
                    <td>
                        <a href="{{ path('job_edit_consultant', {'id': job.id}) }}" class="btn btn-success">Modifier</a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>





    <h1>Liste des annonces qui n'ont pas encore été acceptées par nos équipes :</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Titre de l'annonce</th>
            <th>Description du Poste</th>
            <th>Lieu</th>
            <th>Type de contrat</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Nombre d'heures semaine</th>
            <th>Salaires mensuel</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for job in jobs %}
            {% if job.isAccepted == false %}
                <tr>
                    <td>{{ job.title }}</td>
                    <td>{{ job.description }}</td>
                    <td>{{ job.place }}</td>
                    <td>{{ job.typeContrat }}</td>
                    <td>{{ job.startDate ? job.startDate|date('d-m-Y') : '' }}</td>
                    <td>{{ job.endDate ? job.endDate|date('d-m-Y') : 'Pas de date de fin de contrat' }}</td>
                    <td>{{ job.time }}</td>
                    <td>{{ job.salary }}</td>
                    <td>
                        <a href="{{ path('job_edit_consultant', {'id': job.id}) }}" class="btn btn-success">Modifier</a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    <div>
        <p><a href="{{ path('app') }}" class=" float-end">Retour à la page d'accueil</a></p>
    </div>

{% endblock %}

TRT-Conseil/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

TRT-Conseil/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>

            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Is_accepted</th>
                <td>{{ user.isAccepted ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

TRT-Conseil/templates/user/toApplyJobConsultant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jobs/candidats{% endblock %}

{% block body %}

    <h1>Liste des candidats qui ont postulé pour une ou plusieurs offres.</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Intitulé du job</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for job in jobs %}
            {% for candidate in job.candidates %}
                <tr>
                    <td>{{ candidate.name }}</td>
                    <td>{{ candidate.firstname }}</td>
                    <td>{{ job.title }}</td>
                 <td><a href="{{ path('approving_candidate_job_edit', {'id': job.id , 'cid' : candidate.id}) }}" class="btn btn-primary">Approuver la démarche</a></td>
                </tr>
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}